[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
ANTHROPIC_AUTH_TOKEN = "sk-kimi-wOQeQMaOui7DF2JRn9DUQ5xgpiJ1fQYAigBhodslnb8wtFrmbO6FXsRcLU3DObp8"
ANTHROPIC_BASE_URL = "https://api.kimi.com/coding/"
ANTHROPIC_DEFAULT_SONNET_MODEL = "claude-sonnet-4-6[1m]"
API_TIMEOUT_MS = "3000000"
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "1"
CLAUDE_CODE_EFFORT_LEVEL = "high"
