from __future__ import annotations

import sys


SLICE_BASE_COMMIT = "aaaaeac5747fddc0915a59df34de47e6e8cfec48"
SLICE_NUMBER = 3
SLICE_NAME = "cross-run-resource-admission"
EVIDENCE_PREFIX = "evidence/slice-03/"

EXPECTED_CHECKPOINTS = [
    {"name": "source_ready", "status": "current"},
    {"name": "source_acquisition_decision_ready", "status": "current"},
]

FAULT_POINTS = (
    "after_claim_before_enqueue",
    "after_claim_enqueue_before_schedule",
    "after_claim_schedule_before_commit",
    "after_reclaim_before_enqueue",
    "after_reclaim_enqueue_before_schedule",
    "after_reclaim_schedule_before_commit",
)

RESOURCE_ADMISSION_TEST_TARGETS = (
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_multi_resource_request_is_atomic_and_launch_requires_admission",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_reclaim_invalidates_queued_attempt_and_preserves_admitted_lease",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_launch_authorization_is_resource_bound_and_single_use",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_multi_resource_launch_requires_the_exact_immutable_request",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_crash_after_launch_authorization_cannot_replay_callback",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_two_level_round_robin_is_deterministic_and_survives_restart",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_round_robin_cursor_keeps_position_after_served_identity_dequeues",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_reserved_admission_advances_fairness_cursor_before_next_ordinary_turn",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_zero_quota_rejects_before_claim_or_queue_is_persisted",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_quota_downshift_drains_without_preemption_and_unrelated_work_runs",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_draining_reservations_are_disjoint_and_stably_ordered",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_circuit_breaker_blocks_only_its_resource_class",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_new_reservation_blocks_later_same_pass_overlap",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_unknown_lease_survives_reclaim_until_evidence_bearing_resolution",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_process_and_provider_resolution_require_trusted_verifier_proof",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_local_process_resolution_stays_unknown_while_matching_process_runs",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_resource_resolution_rejects_self_asserted_trust_booleans",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_claim_resource_transaction_faults_roll_back_without_partial_authority",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_reclaim_resource_transaction_faults_roll_back_and_replay_cleanly",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_temporarily_unschedulable_reservation_blocks_full_set_but_not_disjoint_resources",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_resource_control_cli_exposes_public_operational_seams",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_launcher_failure_paths_persist_one_audited_unknown_event_and_remain_fenced",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_stale_claim_after_blocked_launch_callback_commits_unknown_before_conflict",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_launch_completion_with_wrong_lease_generation_has_zero_mutation",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_reconciled_inflight_launch_persists_identity_for_trusted_resolution",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_normal_release_rejects_unverified_provider_result_without_releasing_capacity",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_normal_release_requires_provider_result_bound_to_lease_attempt_and_launch_authority",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_normal_release_accepts_only_trusted_matching_local_process_proof",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_reclaim_advances_claim_and_queues_replacement_when_quota_is_zero",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_provider_resolution_replay_reuses_persisted_proof_before_verifier",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_local_process_resolution_replay_reuses_persisted_proof_before_inspector",
    "tests.video_workflow.test_resource_admission.ResourceAdmissionTests.test_configuration_requires_every_fixed_resource_class_exactly_once",
)

MULTIPROCESS_TEST_TARGETS = (
    "tests.video_workflow.test_resource_admission_multiprocess.ResourceAdmissionMultiprocessTests.test_multi_resource_quota_race_is_atomic_across_processes",
    "tests.video_workflow.test_resource_admission_multiprocess.ResourceAdmissionMultiprocessTests.test_same_task_claim_race_has_exactly_one_owner",
    "tests.video_workflow.test_resource_admission_multiprocess.ResourceAdmissionMultiprocessTests.test_launch_race_invokes_callback_exactly_once_across_processes",
    "tests.video_workflow.test_resource_admission_multiprocess.ResourceAdmissionMultiprocessTests.test_hard_crash_after_callback_cannot_replay_launch",
)

CONTROL_STORE_INTEGRITY_TEST_TARGETS = (
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_missing_lease_resource_or_required_index_fails_closed",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_configuration_and_queue_lease_tampering_fails_closed",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_queue_and_normalized_lease_double_tamper_breaks_request_binding",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_real_v7_store_migrates_atomically_to_complete_v8",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_partial_v8_resource_migration_fails_closed_without_repairing_it",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_resource_schema_and_sequence_authorities_are_closed_and_exact",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_lease_launch_and_terminal_state_matrix_rejects_double_tamper",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_event_cursor_and_breaker_identity_tampering_fails_closed",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_queue_and_reservation_lifecycle_tampering_fails_closed",
    "tests.video_workflow.test_resource_control_store_integrity.ResourceControlStoreIntegrityTests.test_append_only_resource_sequence_gaps_fail_closed",
)

CONTROL_STORE_RECOVERY_TEST_TARGETS = (
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_backup_uses_sqlite_backup_api_and_passes_integrity",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_reconciles_every_run_through_public_kernel_authority",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_orphaned_filesystem_commit_blocks_global_mutation_after_restore",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_missing_corrupt_and_schema_mismatched_backups_fail_closed",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_requires_quiescence_and_explicit_selected_backup",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_corrupt_live_store_uses_atomic_quarantine_and_persists_failure_evidence",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_recovers_every_persistent_state_boundary",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_subsequent_orphan_records_task_staging_and_preservation_evidence",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_repairs_one_record_ahead_windows",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_survives_partial_publication",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_cli_recovers_hard_exit_and_fences_concurrency",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_rejects_impossible_authority_and_report_drift",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_repairs_initial_sentinel_before_prepared_history",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_preserves_resource_transition_evidence_after_hard_exit",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_repairs_blocked_state_ahead_and_preserves_report_bindings",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_rejects_non_file_active_sentinel_authority",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_recovery_contract_rejects_contradictory_resource_inventory",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_resume_rejects_windows_junction_authority_boundaries",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_lock_rechecks_open_handle_path_identity",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_first_restore_path_revalidates_committed_report_before_archive",
    "tests.video_workflow.test_control_store_recovery.ControlStoreRecoveryTests.test_restore_busy_quiescence_failure_does_not_quarantine_or_publish",
)

EXIT_EVIDENCE_TEST_TARGETS = (
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_schema_requires_first_class_result_kinds",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_semantics_bind_exact_results_commands_and_fqn_targets",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_semantics_reject_unbound_result_fixture",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_collector_registers_ten_closed_commands_and_correct_paths",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_collector_logs_include_exact_implementation_marker",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_collector_refuses_dirty_implementation_head",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_validator_rejects_missing_or_wrong_log_commit_marker",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_validator_binds_six_fault_points_to_admission_log",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_closed_test_targets_and_fixtures_resolve",
    "tests.video_workflow.test_issue6_exit_evidence.Slice3ExitEvidenceTests.test_slice3_fixed_base_is_registered_exactly",
)

COMMANDS = (
    (
        "slice0-regression",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "tests.video_workflow.test_legacy_baseline",
        ),
    ),
    (
        "slice3-contracts",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "scripts/video_workflow.py",
            "contracts-check",
        ),
    ),
    (
        "slice1-regression",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "tests.video_workflow.test_source_ready_tracer",
            "tests.video_workflow.test_source_ready_hardening",
            "tests.video_workflow.test_issue4_gate4",
            "tests.video_workflow.test_issue4_gate7",
        ),
    ),
    (
        "slice2-regression",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "tests.video_workflow.test_task_promotion",
            "tests.video_workflow.test_task_promotion_hardening",
            "tests.video_workflow.test_issue5_review_repairs",
            "tests.video_workflow.test_control_store_transaction_scope",
        ),
    ),
    (
        "slice3-resource-admission",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "-v",
            *RESOURCE_ADMISSION_TEST_TARGETS,
            *MULTIPROCESS_TEST_TARGETS,
            *CONTROL_STORE_INTEGRITY_TEST_TARGETS,
        ),
    ),
    (
        "slice3-control-store-recovery",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "-v",
            *CONTROL_STORE_RECOVERY_TEST_TARGETS,
        ),
    ),
    (
        "slice3-exit-evidence-contracts",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-m",
            "unittest",
            "-v",
            *EXIT_EVIDENCE_TEST_TARGETS,
        ),
    ),
    (
        "slice2-exit-evidence",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "scripts/validate_slice_exit_evidence.py",
            "evidence/slice-02/exit-evidence-manifest.json",
        ),
    ),
    (
        "slice3-syntax",
        (
            sys.executable,
            "-X",
            "utf8",
            "-B",
            "-c",
            (
                "import ast,pathlib;"
                "p=list(pathlib.Path('src/video2pdf_workflow_kernel').rglob('*.py'))+"
                "[pathlib.Path('scripts/video_workflow.py'),"
                "pathlib.Path('scripts/validate_slice_exit_evidence.py'),"
                "pathlib.Path('scripts/slice3_exit_evidence_contract.py'),"
                "pathlib.Path('scripts/collect_slice3_exit_evidence.py'),"
                "pathlib.Path('tests/video_workflow/test_issue6_exit_evidence.py')];"
                "[ast.parse(x.read_text(encoding='utf-8'),filename=str(x)) for x in p];"
                "print(f'AST_OK {len(p)}')"
            ),
        ),
    ),
    (
        "slice3-diff-check",
        ("git", "diff", "--check", f"{SLICE_BASE_COMMIT}...HEAD"),
    ),
)

RESULTS = {
    "positive": [
        "all_seven_resource_classes_are_launch_guarded",
        "exact_immutable_resource_request_controls_launch",
        "resource_and_platform_breakers_preserve_unrelated_progress",
        "resource_schema_and_sequence_authorities_are_closed_and_exact",
        "public_resource_operations_are_cli_accessible",
        "public_restore_resume_cli_is_operational",
        "trusted_matching_local_process_proof_releases_normal_lease",
    ],
    "negative": [
        "post_authorization_crash_cannot_replay_launch",
        "zero_quota_fails_before_claim_or_queue",
        "self_asserted_resolution_trust_is_rejected",
        "missing_resource_schema_or_index_fails_closed",
        "configuration_queue_and_lease_tampering_fails_closed",
        "normalized_request_double_tamper_fails_closed",
        "partial_v8_resource_migration_fails_closed",
        "lease_launch_terminal_double_tamper_fails_closed",
        "event_cursor_breaker_identity_tamper_fails_closed",
        "launcher_exception_or_invalid_identity_commits_unknown_lease",
        "queue_and_reservation_lifecycle_tampering_fails_closed",
        "append_only_sequence_gap_or_exhaustion_fails_closed",
        "invalid_restore_lock_or_committed_report_drift_fails_closed",
        "unverified_provider_result_cannot_release_capacity",
        "non_file_active_restore_sentinel_authority_fails_closed",
        "contradictory_resource_inventory_contract_is_rejected",
        "windows_junction_restore_authority_is_rejected",
        "first_restore_committed_report_drift_blocks_archive",
        "busy_quiescence_failure_does_not_quarantine_or_publish",
        "duplicate_resource_class_configuration_is_rejected",
    ],
    "quota": [
        "atomic_multi_resource_admission",
        "overcommitted_quota_downshift_drains",
        "multiprocess_file_backed_quota_never_oversubscribes",
        "quota_zero_reclaim_advances_claim_and_queues_replacement",
    ],
    "fencing": [
        "reclaim_preserves_prior_physical_lease",
        "unknown_lease_remains_capacity_bearing_until_resolution",
        "resolution_evidence_is_trusted_and_identity_bound",
        "same_task_claim_race_has_exactly_one_owner",
        "launch_authority_is_single_use_across_processes",
        "failed_launcher_consumes_authority_and_remains_fenced",
        "stale_launch_confirmation_is_fenced_after_unknown_commit",
        "reclaimed_attempt_status_projection_remains_fenced",
        "wrong_generation_launch_completion_has_zero_mutation",
        "concurrent_restore_resume_is_fenced_by_operation_lock",
        "provider_terminal_result_is_bound_to_lease_attempt_and_launch_authority",
        "restore_lock_open_handle_path_identity_is_rechecked",
    ],
    "fairness": [
        "two_level_run_and_batch_round_robin",
        "cursor_position_survives_served_identity_dequeue",
        "reserved_admission_advances_fairness_cursor",
        "disjoint_reservations_follow_stable_sequence",
        "new_active_reservation_blocks_same_pass_overlap",
        "active_reservation_blocks_its_full_set_while_disjoint_resources_progress",
    ],
    "restart": [
        "scheduler_cursor_and_sequence_rehydrate",
        "reservation_state_and_sequence_rehydrate",
        "breaker_scope_and_state_rehydrate",
        "unknown_capacity_rehydrates",
        "hard_crash_launch_authority_cannot_replay_after_restart",
        "claim_resource_fault_restart_has_no_partial_authority",
        "launcher_failure_unknown_state_rehydrates_and_cannot_replay",
        "restore_resume_converges_from_every_persistent_boundary",
        "state_sentinel_half_write_windows_are_repaired",
        "partial_control_store_publication_resumes",
        "hard_exit_restore_resume_converges_via_public_cli",
        "initial_sentinel_before_prepared_history_resumes_via_public_cli",
        "resource_transition_reconciliation_resumes_after_hard_exit",
        "blocked_state_ahead_window_resumes",
        "provider_resolution_replay_reuses_persisted_proof",
        "local_process_resolution_replay_reuses_persisted_proof",
        "busy_quiescence_prepared_restore_resumes_after_contention",
    ],
    "recovery": [
        "sqlite_backup_api_snapshot_passes_integrity",
        "explicit_restore_uses_public_kernel_reconciliation",
        "orphaned_filesystem_commit_blocks_global_mutation",
        "invalid_backup_classes_fail_closed",
        "restore_requires_quiescence_and_explicit_backup",
        "matching_process_stays_unknown_until_trusted_termination_proof",
        "v7_resource_store_migrates_atomically_to_v8",
        "reclaim_resource_fault_replay_converges_cleanly",
        "post_backup_live_resource_inventory_is_reported_exactly",
        "severe_live_store_corruption_is_atomically_quarantined",
        "orphan_blocking_evidence_is_exact_and_durable",
        "subsequent_orphan_staging_and_preservation_evidence_is_exact",
        "reconciled_inflight_launch_identity_supports_trusted_resolution",
        "resource_transition_evidence_survives_reconcile_hard_exit",
        "blocked_recovery_and_orphan_reports_remain_hash_bound",
        "first_restore_report_revalidation_preserves_resumable_authority",
    ],
}


def _binding(
    result_id: str, result_kind: str, command_id: str, test_target: str
) -> dict[str, str]:
    return {
        "result_id": result_id,
        "result_kind": result_kind,
        "command_id": command_id,
        "test_target": test_target,
    }


RESULT_BINDINGS = [
    _binding(
        "all_seven_resource_classes_are_launch_guarded",
        "positive",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[2],
    ),
    _binding(
        "exact_immutable_resource_request_controls_launch",
        "positive",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[3],
    ),
    _binding(
        "resource_and_platform_breakers_preserve_unrelated_progress",
        "positive",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[11],
    ),
    _binding(
        "resource_schema_and_sequence_authorities_are_closed_and_exact",
        "positive",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[5],
    ),
    _binding(
        "public_resource_operations_are_cli_accessible",
        "positive",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[20],
    ),
    _binding(
        "public_restore_resume_cli_is_operational",
        "positive",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[10],
    ),
    _binding(
        "trusted_matching_local_process_proof_releases_normal_lease",
        "positive",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[27],
    ),
    _binding(
        "post_authorization_crash_cannot_replay_launch",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[4],
    ),
    _binding(
        "zero_quota_fails_before_claim_or_queue",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[8],
    ),
    _binding(
        "self_asserted_resolution_trust_is_rejected",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[16],
    ),
    _binding(
        "missing_resource_schema_or_index_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[0],
    ),
    _binding(
        "configuration_queue_and_lease_tampering_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[1],
    ),
    _binding(
        "normalized_request_double_tamper_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[2],
    ),
    _binding(
        "partial_v8_resource_migration_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[4],
    ),
    _binding(
        "lease_launch_terminal_double_tamper_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[6],
    ),
    _binding(
        "event_cursor_breaker_identity_tamper_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[7],
    ),
    _binding(
        "launcher_exception_or_invalid_identity_commits_unknown_lease",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[21],
    ),
    _binding(
        "queue_and_reservation_lifecycle_tampering_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[8],
    ),
    _binding(
        "append_only_sequence_gap_or_exhaustion_fails_closed",
        "negative",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[9],
    ),
    _binding(
        "invalid_restore_lock_or_committed_report_drift_fails_closed",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[11],
    ),
    _binding(
        "unverified_provider_result_cannot_release_capacity",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[25],
    ),
    _binding(
        "non_file_active_restore_sentinel_authority_fails_closed",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[15],
    ),
    _binding(
        "contradictory_resource_inventory_contract_is_rejected",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[16],
    ),
    _binding(
        "windows_junction_restore_authority_is_rejected",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[17],
    ),
    _binding(
        "first_restore_committed_report_drift_blocks_archive",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[19],
    ),
    _binding(
        "busy_quiescence_failure_does_not_quarantine_or_publish",
        "negative",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[20],
    ),
    _binding(
        "duplicate_resource_class_configuration_is_rejected",
        "negative",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[31],
    ),
    _binding(
        "atomic_multi_resource_admission",
        "quota",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[0],
    ),
    _binding(
        "overcommitted_quota_downshift_drains",
        "quota",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[9],
    ),
    _binding(
        "multiprocess_file_backed_quota_never_oversubscribes",
        "quota",
        "slice3-resource-admission",
        MULTIPROCESS_TEST_TARGETS[0],
    ),
    _binding(
        "quota_zero_reclaim_advances_claim_and_queues_replacement",
        "quota",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[28],
    ),
    _binding(
        "reclaim_preserves_prior_physical_lease",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[1],
    ),
    _binding(
        "unknown_lease_remains_capacity_bearing_until_resolution",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[13],
    ),
    _binding(
        "resolution_evidence_is_trusted_and_identity_bound",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[14],
    ),
    _binding(
        "same_task_claim_race_has_exactly_one_owner",
        "fencing",
        "slice3-resource-admission",
        MULTIPROCESS_TEST_TARGETS[1],
    ),
    _binding(
        "launch_authority_is_single_use_across_processes",
        "fencing",
        "slice3-resource-admission",
        MULTIPROCESS_TEST_TARGETS[2],
    ),
    _binding(
        "failed_launcher_consumes_authority_and_remains_fenced",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[21],
    ),
    _binding(
        "stale_launch_confirmation_is_fenced_after_unknown_commit",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[22],
    ),
    _binding(
        "reclaimed_attempt_status_projection_remains_fenced",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[1],
    ),
    _binding(
        "wrong_generation_launch_completion_has_zero_mutation",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[23],
    ),
    _binding(
        "concurrent_restore_resume_is_fenced_by_operation_lock",
        "fencing",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[10],
    ),
    _binding(
        "provider_terminal_result_is_bound_to_lease_attempt_and_launch_authority",
        "fencing",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[26],
    ),
    _binding(
        "restore_lock_open_handle_path_identity_is_rechecked",
        "fencing",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[18],
    ),
    _binding(
        "two_level_run_and_batch_round_robin",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[5],
    ),
    _binding(
        "cursor_position_survives_served_identity_dequeue",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[6],
    ),
    _binding(
        "reserved_admission_advances_fairness_cursor",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[7],
    ),
    _binding(
        "disjoint_reservations_follow_stable_sequence",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[10],
    ),
    _binding(
        "new_active_reservation_blocks_same_pass_overlap",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[12],
    ),
    _binding(
        "active_reservation_blocks_its_full_set_while_disjoint_resources_progress",
        "fairness",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[19],
    ),
    _binding(
        "scheduler_cursor_and_sequence_rehydrate",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[5],
    ),
    _binding(
        "reservation_state_and_sequence_rehydrate",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[10],
    ),
    _binding(
        "breaker_scope_and_state_rehydrate",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[11],
    ),
    _binding(
        "unknown_capacity_rehydrates",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[13],
    ),
    _binding(
        "hard_crash_launch_authority_cannot_replay_after_restart",
        "restart",
        "slice3-resource-admission",
        MULTIPROCESS_TEST_TARGETS[3],
    ),
    _binding(
        "claim_resource_fault_restart_has_no_partial_authority",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[17],
    ),
    _binding(
        "launcher_failure_unknown_state_rehydrates_and_cannot_replay",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[21],
    ),
    _binding(
        "restore_resume_converges_from_every_persistent_boundary",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[6],
    ),
    _binding(
        "state_sentinel_half_write_windows_are_repaired",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[8],
    ),
    _binding(
        "partial_control_store_publication_resumes",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[9],
    ),
    _binding(
        "hard_exit_restore_resume_converges_via_public_cli",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[10],
    ),
    _binding(
        "initial_sentinel_before_prepared_history_resumes_via_public_cli",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[12],
    ),
    _binding(
        "resource_transition_reconciliation_resumes_after_hard_exit",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[13],
    ),
    _binding(
        "blocked_state_ahead_window_resumes",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[14],
    ),
    _binding(
        "provider_resolution_replay_reuses_persisted_proof",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[29],
    ),
    _binding(
        "local_process_resolution_replay_reuses_persisted_proof",
        "restart",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[30],
    ),
    _binding(
        "busy_quiescence_prepared_restore_resumes_after_contention",
        "restart",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[20],
    ),
    _binding(
        "sqlite_backup_api_snapshot_passes_integrity",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[0],
    ),
    _binding(
        "explicit_restore_uses_public_kernel_reconciliation",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[1],
    ),
    _binding(
        "orphaned_filesystem_commit_blocks_global_mutation",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[2],
    ),
    _binding(
        "invalid_backup_classes_fail_closed",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[3],
    ),
    _binding(
        "restore_requires_quiescence_and_explicit_backup",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[4],
    ),
    _binding(
        "matching_process_stays_unknown_until_trusted_termination_proof",
        "recovery",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[15],
    ),
    _binding(
        "v7_resource_store_migrates_atomically_to_v8",
        "recovery",
        "slice3-resource-admission",
        CONTROL_STORE_INTEGRITY_TEST_TARGETS[3],
    ),
    _binding(
        "reclaim_resource_fault_replay_converges_cleanly",
        "recovery",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[18],
    ),
    _binding(
        "post_backup_live_resource_inventory_is_reported_exactly",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[1],
    ),
    _binding(
        "severe_live_store_corruption_is_atomically_quarantined",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[5],
    ),
    _binding(
        "orphan_blocking_evidence_is_exact_and_durable",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[2],
    ),
    _binding(
        "subsequent_orphan_staging_and_preservation_evidence_is_exact",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[7],
    ),
    _binding(
        "reconciled_inflight_launch_identity_supports_trusted_resolution",
        "recovery",
        "slice3-resource-admission",
        RESOURCE_ADMISSION_TEST_TARGETS[24],
    ),
    _binding(
        "resource_transition_evidence_survives_reconcile_hard_exit",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[13],
    ),
    _binding(
        "blocked_recovery_and_orphan_reports_remain_hash_bound",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[14],
    ),
    _binding(
        "first_restore_report_revalidation_preserves_resumable_authority",
        "recovery",
        "slice3-control-store-recovery",
        CONTROL_STORE_RECOVERY_TEST_TARGETS[19],
    ),
]

FIXTURE_SPECS = (
    (
        "immutable_offline_fixture",
        "tests/video_workflow/fixtures/source-ready-tracer/fixture.json",
    ),
    (
        "immutable_offline_fixture",
        "tests/video_workflow/fixtures/source-ready-tracer/metadata/platform.json",
    ),
    (
        "immutable_offline_fixture",
        "tests/video_workflow/fixtures/source-ready-tracer/subtitles/subtitle.en.srt",
    ),
    (
        "immutable_offline_fixture",
        "tests/video_workflow/fixtures/source-ready-tracer/media/video.fixture",
    ),
    (
        "immutable_offline_fixture",
        "tests/video_workflow/fixtures/source-ready-tracer/cover/cover.fixture",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/contracts/resource-admission-configuration.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/contracts/resource-admission-configuration.invalid.json",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/contracts/resource-lease-resolution-evidence.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/contracts/resource-lease-resolution-evidence.invalid.json",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/contracts/subagent-task-envelope.v2.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/contracts/subagent-task-envelope.v2.invalid.json",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/contracts/control-store-backup-manifest.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/contracts/control-store-backup-manifest.invalid.json",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/contracts/control-store-recovery-report.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/contracts/control-store-recovery-report.invalid.json",
    ),
    (
        "positive_schema_fixture",
        "tests/video_workflow/fixtures/exit_evidence_manifest.v2.slice3.valid.json",
    ),
    (
        "negative_schema_fixture",
        "tests/video_workflow/fixtures/exit_evidence_manifest.v2.slice3.missing-domain.invalid.json",
    ),
    (
        "negative_semantic_fixture",
        "tests/video_workflow/fixtures/exit_evidence_manifest.v2.slice3.unbound-result.invalid.json",
    ),
)
